### PR TITLE
Normalize ruamel types returned by load_yaml_files

### LINKED ISSUE #47: load_yaml_files leaks ruamel Commented* types (breaks downstream .get())
Consumers of nac_yaml.yaml.load_yaml_files() previously received plain dict/list structures (e.g. in v1.1.1). In current 2.x, the returned data can contain ruamel.yaml.comments.CommentedSeq/CommentedMap. This breaks downstream code that expects list elements to be dicts (e.g. p.get("name")), causing AttributeError: 'CommentedSeq' object has no attribute 'get'.

Fix: normalize output once at end of load_yaml_files() by deep-converting CommentedMap -> dict and CommentedSeq -> list (single O(N) walk). Added unit test to reproduce the .get() failure mode and ensure compatibility.

Found this in nac-sdwan validation:

1. works with nac-yaml 1.1.1:

```
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$ pytest -m validate
============================================================== test session starts ==============================================================
platform darwin -- Python 3.12.10, pytest-9.0.3, pluggy-1.6.0
rootdir: /Users/oboehmer/Documents/DD/nac-sdwan
configfile: pyproject.toml
plugins: cov-4.1.0, anyio-4.13.0
collected 4 items / 2 deselected / 2 selected

tests/integration/test_validation.py ..                                                                                                   [100%]

======================================================== 2 passed, 2 deselected in 1.88s ========================================================
```
2. Breaks after installing 2.0.0a0
```
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$ uv pip install nac-yaml==2.0.0a0
Resolved 3 packages in 19ms
Uninstalled 1 package in 1ms
Installed 1 package in 3ms
 - nac-yaml==1.1.1
 + nac-yaml==2.0.0a0
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$ pytest -m validate
============================================================== test session starts ==============================================================
platform darwin -- Python 3.12.10, pytest-9.0.3, pluggy-1.6.0
rootdir: /Users/oboehmer/Documents/DD/nac-sdwan
configfile: pyproject.toml
plugins: cov-4.1.0, anyio-4.13.0
collected 4 items / 2 deselected / 2 selected

tests/integration/test_validation.py .F                                                                                                   [100%]

=================================================================== FAILURES ====================================================================
______________________________________________________ test_sdwan_validation[data_paths1] _______________________________________________________

data_paths = ['tests/integration/fixtures/sdwan/standard/', 'tests/integration/fixtures/sdwan/standard_2015/']

    @pytest.mark.parametrize(
        "data_paths",
        [
            (
                [
                    "tests/integration/fixtures/sdwan/standard/",
                    "tests/integration/fixtures/sdwan/standard_2012/",
                ]
            ),
            (
                [
                    "tests/integration/fixtures/sdwan/standard/",
                    "tests/integration/fixtures/sdwan/standard_2015/",
                ]
            )
        ],
    )
    def test_sdwan_validation(data_paths):
        validator = Validator(SCHEMA_PATH, VALIDATION_RULES_PATH)
        validator.validate_syntax(data_paths)
        if validator.errors:
            pytest.fail("Syntactic validation has failed.")
>       validator.validate_semantics(data_paths)

tests/integration/test_validation.py:36:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv/lib/python3.12/site-packages/nac_validate/validator.py:171: in validate_semantics
    paths = rule.match(self.data)
            ^^^^^^^^^^^^^^^^^^^^^
validation/rules/401_Configuration_groups.py:1044: in match
    find_profile = next((p for p in feature_profiles if p.get('name') == config_group.get(cfg_grp_profile_type)), None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <list_iterator object at 0x10a1cdf30>

>   find_profile = next((p for p in feature_profiles if p.get('name') == config_group.get(cfg_grp_profile_type)), None)
                                                        ^^^^^
E   AttributeError: 'CommentedSeq' object has no attribute 'get'

validation/rules/401_Configuration_groups.py:1044: AttributeError
============================================================ short test summary info ============================================================
FAILED tests/integration/test_validation.py::test_sdwan_validation[data_paths1] - AttributeError: 'CommentedSeq' object has no attribute 'get'
=================================================== 1 failed, 1 passed, 2 deselected in 1.81s ===================================================
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$ 
```

### PR DESCRIPTION
**Pull request by oboehmer**
## Summary
- Deep-convert ruamel CommentedMap/CommentedSeq to plain dict/list before returning from load_yaml_files.
- Add regression test covering downstream `.get()` failure mode.

Fixes #47.

## Test plan
- [x] uv run mypy nac_yaml
- [x] uv run pytest -q

Tested the fix with the failing nac-sdwan data:

1. Failing:

```
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$ nac-validate --schema schemas/schema.yaml --rules validation/rules/ tests/integration/fixtures/sdwan/standard_2015/
ERROR - Unexpected error: 'CommentedSeq' object has no attribute 'get'
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$
```

2. with the fix:
```
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$ nac-validate --schema schemas/schema.yaml --rules validation/rules/ tests/integration/fixtures/sdwan/standard_2015/
(.venv) OBOEHMER-M-5D76:nac-sdwan oboehmer$ echo $?
0
```

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by oboehmer** [comment]
Follow-up finding from nac-sdwan validation rule: the immediate trigger was a strict type check .

When nac-yaml returned ruamel , this check evaluated false and wrapped the sequence: , creating an extra nesting layer. Downstream then iterated that outer list and did  where  was a  (no ), causing the AttributeError.

Changing downstream to  fixes the crash as well.

So: nac-yaml output normalization restores the previous contract (plain list/dict), but some consumers may still want to avoid  checks when loading YAML.

**Comment by oboehmer** [comment]
closing this PR, downstream consumers need to fix their code

**Comment by danischm** [comment]
Using `CommentedMap`/`CommentedSeq` is deliberate to retain extra data such as YAML comments.
